### ISSUE TITLE
Support ImageStream as a source input

### ISSUE THREAD

**Issue by arthurdm** [appsody/appsody-operator#115]
When someone uses `s2i` they usually always use 3 types of resources:
- a `BuildConfig`, with the `s2i` build strategy
- an `ImageStream`, which is the output of the `BuildConfig`
- a `DeploymentConfig`, which configures the deployment of the `ImageStream`

Our operator is much like the `DeploymentConfig`, but with more features.  

For customers that have chosen this path, they could benefit from swapping a `DeploymentConfig` for an `AppsodyApplication`.

One of the interesting things about `DeploymentConfig` is that it can react to a trigger, like the `ImageStream` being updated.  We need to also support this.

**Comment by navidsh** [comment]
Putting this on-hold to post `0.3.0`. A prototype is added into https://github.com/appsody/appsody-operator/tree/s2i

**Comment by arthurdm** [comment]
thanks @navidsh - I have thought more about this feature and changed its scope.  I am not sure there would be much value in us just replicating that `BuildConfig` does - I believe our value-add is in just replacing `DeploymentConfig`.   Appsody's build flow is what would be more suitable for integrating with a `BuildConfig` (with `s2i`) approach.

**Comment by arthurdm** [comment]
placing this back into the backlog for now.

**Comment by arthurdm** [comment]
targeted this for the next release.

Essentially this work should allow customers to update the application container image (for example, with a security patch / ifix) and this change in the ImageStream would trigger our operator to roll out the update.   This saves the customer from having to update their `app-deploy.yaml` and doing another manual `oc apply` (or equivalent).

**Comment by navidsh** [comment]
Pushed all changes to `application-stacks/operator`. Closing.
