### ISSUE TITLE
Image pull policy with the Appsody operator

### ISSUE THREAD

**Issue by chilanti** [appsody/appsody-operator#137]
## Type of question

General context

## Question
Does the appsody operator support the various `imagePullPolicy` options?
We get `IfNotPresent` by default, but being able to pick would be desirable. Not sure if the `AppsodyApplication` CRs support that field.

**Comment by arthurdm** [comment]
hey @chilanti - yup, you can configure it via the `pullPolicy` key in your CR: https://github.com/appsody/appsody-operator/blob/master/deploy/crds/appsody_v1beta1_appsodyapplication_crd.yaml#L262

**Comment by chilanti** [comment]
Nice.... I'll update `appsody deploy` to set it to `Always`.
