### ISSUE TITLE
Add tests for ServiceMonitor creation support

### ISSUE THREAD

**Issue by navidsh** [appsody/appsody-operator#139]
I'd suggest we add unit tests given that the service monitor creation logic is isolated in `pkg/utils/utils.go:CustomizeServiceMonitor`.

**Update:** Add both unit and e2e tests. e2e tests are important to add since it covers the CRD validation part.

**Comment by arturdzm** [comment]
Possibly can enable JWT security using  this ServiceAccount  token /var/run/secrets/kubernetes.io/serviceaccount/token
