### ISSUE TITLE
Build multi-arch Docker image for Appsody operator

### ISSUE THREAD

**Issue by navidsh** [appsody/appsody-operator#146]
Support building multi-arch image for the Appsody operator. The challenge is that, at of now, public Travis doesn't have Z and Power environments to build on.

Investigation needed:
- Can we use a combination of public Travis and internal Travis to achieve this?

**Comment by arthurdm** [comment]
thanks for opening this one Navid.  Another point to investigate is if (or when) Red Hat's registry will allow multi-arch images.   I believe right now it doesn't support a FAT manifest. This affects our certified version.

**Comment by edavidj** [comment]
Multi-arch images are now pushed. I'll watch for updates on the Red Hat Registry manifest list support issue, and can open another issue to track progress on that
