### ISSUE TITLE
Add must gather scripts for Appsody

### ISSUE THREAD

**Issue by navidsh** [appsody/appsody-operator#148]
Add must-gather scripts to Appsody to help troubleshoot issues. As part of this, [doc/troubleshooting.md](https://github.com/appsody/appsody-operator/blob/master/doc/troubleshooting.md) should be updated to help users find problems using the must-gather scripts.

**Comment by sympatheticmoose** [comment]
@navidsh to be clear - are you suggesting this for Appsody or just the Operator?

**Comment by navidsh** [comment]
@sympatheticmoose  just the operator. We might look at something like https://github.com/navidsh/kabanero-must-gather for collecting mustgather. Still looking  at the options on this
