### ISSUE TITLE
Ensure Appsody operator is supported in OCP 4.2

### ISSUE THREAD

**Issue by navidsh** [appsody/appsody-operator#154]
This issue is to ensure the Appsody operator runs smoothly in OCP 4.

**Comment by arthurdm** [comment]
Let's make sure we test OpenShift 4.2

**Comment by navidsh** [comment]
Things to test:
- [ ] Knative
- [ ] Running e2e tests
- [ ] Storage
- [ ] kAppNav
- Installing the Operator 
  - [ ] Appsody CLI
  - [ ] Instructions on the repo

**Comment by leochr** [comment]
Verified.
