### ISSUE TITLE
Add support for init containers

### ISSUE THREAD

**Issue by chilanti** [appsody/appsody-operator#161]
### Is your feature request related to a problem?

One of the K8S capabilities we are planning to use to enable Appsody to run on K8S is the use of init containers. For instance, an init container can be bundled within the same pod as the Appsody stack (which can't be modified) to perform actions such as pulling the appropriate version of the Appsody controller for the app container to use.

The CRD of an AppsodyApplication doesn't seem to support init containers.

### Describe the solution you'd like

Add init container support.

**Comment by arthurdm** [comment]
Thanks @chilanti - would you guys need to pass in a `command` as well, or just the init container image?

@navidsh / @leochr / @arturdzm - is there an init container object that would make this an easy capability to add?

**Comment by navidsh** [comment]
`InitContainers` in `Deployment` or `StatefulSet` accepts a list of `Container`s so we can accept the list in the CRD.

I guess we need to decide if we want to have a general-purpose `InitContainers` field in the CRD or just accepting a few fields. And the design depends on which [fields](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.14/#container-v1-core) need to be passed in.

Plus, I didn't find a way to specify `InitContainers` for Knative Service. What should operator do in that case?

**Comment by chilanti** [comment]
@arthurdm - yes, we'd need to pass a `command` too with `args`.

**Comment by leochr** [comment]
@chilanti We'll add support to specify an array of init containers (as YAML object - similar to `volumeMounts` field). It'll be supported for `Deployment`/`StatefulSet` but not with Knative at this time.

@arturdzm As we discussed yesterday, this is needed for the Appsody operator release v0.3.0 on Monday. Could you please add this support?

**Comment by arturdzm** [comment]
Delivered in 0.3.0
