### ISSUE TITLE
Support for operator-sdk version v0.11.0

### ISSUE THREAD

**Issue by kyleschlosser** [appsody/appsody-operator#164]
Upgrading to operator-sdk version 0.11.0 results in the following validation errors: 
```
API rule violation: list_type_missing,./pkg/apis/appsody/v1beta1,AppsodyApplicationSpec,Architecture
API rule violation: list_type_missing,./pkg/apis/appsody/v1beta1,AppsodyApplicationSpec,Env
API rule violation: list_type_missing,./pkg/apis/appsody/v1beta1,AppsodyApplicationSpec,EnvFrom
API rule violation: list_type_missing,./pkg/apis/appsody/v1beta1,AppsodyApplicationSpec,VolumeMounts
API rule violation: list_type_missing,./pkg/apis/appsody/v1beta1,AppsodyApplicationSpec,Volumes
API rule violation: list_type_missing,./pkg/apis/appsody/v1beta1,AppsodyApplicationStatus,Conditions
```

That validation rule is found here: https://github.com/kubernetes/kube-openapi/blob/master/pkg/generators/rules/idl_tag.go

The referenced IDL type which is missing is described here: 
https://godoc.org/k8s.io/kube-openapi/pkg/idl#ListType

What is missing is the annotations like `+listType=map`

**Comment by arturdzm** [comment]
Operator was updated to 0.12.0 in release 0.3.0
