### ISSUE TITLE
Appsody Stack Label

### ISSUE THREAD

**Issue by EnriqueL8** [appsody/appsody-operator#165]
## Question
We are currently working on adding labels from Appsody to the custom resource. Within these labels, we have a series of stack labels with prefix `dev.appsody.stack`. Currently the operator is creating a label: `labels["app.appsody.dev/stack"] = cr.Spec.Stack` [here](https://github.com/appsody/appsody-operator/blob/master/pkg/apis/appsody/v1beta/appsodyapplication_types.go#L520). 
This results in a mismatch between the labels produced by Appsody, and this label added by the Operator. Is there a reason being the format of this label?

**Comment by leochr** [comment]
@EnriqueL8 No particular reason for the naming of the label. We thought it'll be good to add the stack information to the resources that the Appsody operator creates. There were no guidelines/suggestions for labels at that time, so we choose `app.appsody.dev/stack`. We can change it to match a label that you suggest or not set a label at all. Please advise. Thanks.

**Comment by EnriqueL8** [comment]
Thanks for the clarification @leochr. I think we would remove it once the labels from Appsody are propagated correctly to CR. @kylegc What do you think?

**Comment by kylegc** [comment]
I'd recommend we change the label to `dev.appsody.stack.id` to be consistent with the appsody image labels. 

@leochr is this one of the labels that the operator copies to all spawned resources? Or does the operator copy all AppsodyApplication labels to spawned resources?

**Comment by leochr** [comment]
@kylegc The operator adds the labels specified on AppsodyApplication (under `metadata.labels`) to all resources it creates. When the `Stack` parameter is specified, label `app.appsody.dev/stack` is added to the metadata with the specified value. Detailed information on labels is available [here](https://github.com/appsody/appsody-operator/blob/master/doc/user-guide.md#labels)

FYI, the value of the `Stack` parameter is also used as the key to lookup stack data from the ConfigMaps for [constants](https://github.com/appsody/appsody-operator/blob/master/deploy/stack_constants.yaml) and [defaults](https://github.com/appsody/appsody-operator/blob/master/deploy/stack_defaults.yaml) (Champ would configure those). It supports any stack values. But the default maps we create just use the plain stack name as keys (i.e.`java-microprofile`).

**Comment by arthurdm** [comment]
hey guys - thinking more about this, I think we should consider following the Kubernetes label [convention](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set), which usually have a DNS subdomain as prefix, the a slash `/`, then the name.  Such as [these examples](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels).

I believe that's the rationale for `app.appsody.dev/stack`.  

So I wonder if the Appsody CLI should have a conversion scheme for transforming the OCI labels in the docker image to k8s labels in the AppsodyApplication CR, so that it's closer to what other k8s labels look like?

**Comment by navidsh** [comment]
We picked the `app.appsody.dev/XYZ` format based on [a paragraph from kubernetes.io](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels) :

> Shared labels and annotations share a common prefix: `app.kubernetes.io`. **Labels without a prefix are private to users**. The shared prefix ensures that shared labels do not interfere with custom user labels.


And also we checked other projects:
```
Knative                 serving.knative.dev/visibility: cluster-local
                        eventing.knative.dev/release: devel
                        serving.knative.dev/release: v0.6.0

OpenShift               node.openshift.io/os_id: rhcos
                        openshift.io/component: network

Kubernetes              beta.kubernetes.io/os: linux
                        kubernetes.io/arch: amd64
                        app.kubernetes.io/name: mysql
                        app.kubernetes.io/instance: wordpress-abcxzy
                        statefulset.kubernetes.io/pod-name: alertmanager-main-0
```

**Comment by EnriqueL8** [comment]
I also prefer the third option, since it aligns more closely to the k8s and openshift conventions.

**Comment by arthurdm** [comment]
+1

**Comment by kylegc** [comment]
Operator team, given the discussion above, we have chosen the label prefix `stack.appsody.dev/` for stack information. We will add the following labels:
```
    stack.appsody.dev/tag: appsody/nodejs-express:0.2.7
    stack.appsody.dev/id: nodejs-express
```

Please remove your usage of the label `app.appsody.dev/stack`.

Thanks

**Comment by leochr** [comment]
@kylegc sure, we'll make the change to switch to the new label. Thanks.
