### ISSUE TITLE
Modify some of the app labels

### ISSUE THREAD

**Issue by arthurdm** [appsody/appsody-operator#179]
**As-is**:  we set `app.kubernetes.io/name` to be the same as `metadata.name` and don't allow that to be overridden. 

**To-be**: set `app.kubernetes.io/instance` to be the same as `metadata.name` and let `app.kubernetes.io/name` be configurable by the CR (default could still be `metadata.name`)

**Comment by arthurdm** [comment]
@kylegc / @seabaylea - as per our slack chat.

**Comment by kylegc** [comment]
Thanks!
