### ISSUE TITLE
appsody-operator does not watch child ksvc for re-create / reconcile

### ISSUE THREAD

**Issue by dacleyra** [appsody/appsody-operator#184]
### What did you do?

Create an appsodyapplication and enable knative service `spec.createKnativeService: true`
Observe there is a ksvc for the appsodyapplication `oc get ksvc`
Delete the ksvc `oc delete ksvc name`

### What did you expect to see?

Expect that the ksvc would be recreated by watch / reconcile

### What did you see instead?

*crickets*

however, deleting the appsody-operator causes a re-reconcile which will re-create the ksvc

### Environment

* Appsody CLI version: 0.4.10

* Appsody Stack: nodejs

* Kubernetes version information: OCP 4.2

Client Version: v4.3.0
Server Version: 4.2.0
Kubernetes Version: v1.14.6+2e5ed54

### Possible solution

Watch for owned ksvc object, example
https://github.com/kabanero-io/kabanero-operator/blob/master/pkg/controller/collection/collection_controller.go#L80

**Comment by arturdzm** [comment]
This is functionality that operator is lacking in general right now, regardless of use of Knative.

**Comment by arturdzm** [comment]
Should be fixed in next release
