### ISSUE TITLE
Environment variables with envFrom is not accepted.

### ISSUE THREAD

**Issue by haveroot** [appsody/appsody-operator#200]
### What did you do?

Following the example as described in [Environment Variables](https://github.com/appsody/appsody-operator/blob/master/doc/user-guide.md#environment-variables), I added environment variables as shown below.

```yaml
  envFrom:
    - configMapRef:
      name: some.cfgmap
    - secretRef:
      name: some.secret
```

`appsody deploy` fails with this message 

```bash
spec.envFrom.configMapRef in body must be of type object: "null"
spec.envFrom.secretRef in body must be of type object: "null"
```

The above error message is actually consistent with the description of `envFrom` in the CR descripion [table](https://github.com/appsody/appsody-operator/blob/master/doc/user-guide.md#custom-resource-definition-crd).

### What did you expect to see?

Successful appsody deployment

### What did you see instead?

Failed appsody deployment

### Environment

* Appsody CLI version: `0.5.3`

* Appsody Stack: Custom

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2018-10-10T16:38:01Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-10-31T21:06:55Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by arturdzm** [comment]
`envFrom` is used to mount `all` keys from config map as env variable, therefore it has no name for variable itself:

This example is correct:

```
envFrom:
  - configMapRef:
      name: env-configmap
```
if you want to mount only 1 specific key from map/secret `env` is used.

It is correctly documented in user guide

**Comment by chainhead** [comment]
Under Environment Variables, yes. But, in the table for CRD, here is what we have:

> An array of environment variables following the format of {name, valueFrom}, where valueFrom is YAML object containing a property named either secretKeyRef or configMapKeyRef, which in turn contain the properties name and key.

I think, a better wording would be:

> An array of environment variables following the format of {name, valueFrom}, where valueFrom is YAML object containing a property named either secretKeyRef or configMapKeyRef with value as the actual secret object or configuration map object respectively.
