### ISSUE TITLE
Operator fails install to a specified namespace when query of all-namespaces is restricted

### ISSUE THREAD

**Issue by richard-trotter** [appsody/appsody-operator#201]
## Bug Report

I recently received notice of some RHOCP enablement resources, including a course on OpenShift 4. The course includes labs that use a provided RHOCP shared cluster. Since IBM Public Cloud does not provide an OpenShift Lite (free) option, this cluster seemed like a good place to evaluate deployment of an AppsodyApplication to an OpenShift cluster. Of course this requires installation of the Appsody Operator. 

I can only install resources to my own namespace, and installation of Appsody to my own namespace fails.

It looks like this is failing while trying to determine if the operator is already installed, and is failing because 'get pods' is run with '-all-namespaces' but I don't have auth (in this shared cluster) to query all namespaces.  Seems like a bug, that '-all-namespaces'  is used instead of '--namespace eda4-appsody-deployment '.
$ appsody operator install --namespace eda4-appsody-deployment --verbose
...
[Debug] watchNamespace is:  eda4-appsody-deployment
[Info] Running command: kubectl get deployments -o=jsonpath='{.items[?(@.metadata.name=="appsody-operator")].metadata.namespace}' -n eda4-appsody-deployment
[Info] There are no deployments with appsody-operator
[Debug] Looking for an operator matching watchspace: eda4-appsody-deployment
[Info] Running command: kubectl get pods -o=jsonpath='{.items[?(@.metadata.labels.name=="appsody-operator")].metadata.namespace}' --all-namespaces
[Error] kubectl command failed: ''

### Environment

* Appsody CLI version: 0.5.3

* Appsody Stack: java-spring-boot2

* Kubernetes version information: 
$ oc version --short
Client Version: v4.0.22
Server Version: v1.13.4+28c3de7

**Comment by arturdzm** [comment]
The installation code you referring to is in Appsody CLI
https://github.com/appsody/appsody

**Comment by leochr** [comment]
Issue moved to [appsody/appsody #813](https://github.com/appsody/appsody/issues/813) via [**ZenHub**](https://www.zenhub.com/)
