### ISSUE TITLE
Add Contributor Agreement to Appsody-Operator Repository

### ISSUE THREAD

**Issue by hsaunders0788** [appsody/appsody-operator#205]
Need to add and implement a contributor agreement and check that all contributors have signed off.

See parent epic for more information: https://github.ibm.com/WASCloudPrivate/roadmap-cloudpaks/issues/679

**Comment by JusteenR** [comment]
@hsaunders0788  @arthurdm What address should we ask the contributor to send the license agreements to once they sign them? In the open liberty repository they use cla@openliberty.io in https://github.com/OpenLiberty/open-liberty/blob/master/cla/open-liberty-cla-individual.pdf

**Comment by hsaunders0788** [comment]
That's a good question. We might be able to piggyback off of that for the OpenLiberty Docker and Operator, but I'm not sure it makes sense for the appsody operator or tWAS Docker. 

@arthurdm maybe we could set up an IBM or other kind of email for folks to use?

Otherwise, we could probably put a particular person in charge of it but need to make sure we update that email if that person leaves the team ever.

**Comment by hsaunders0788** [comment]
Another option is to follow what the IBM Open Source communities do like in this template repo: 

https://github.com/IBM/repo-template/blob/master/CONTRIBUTING.md

They don't have them email, but instead have them add to their commit messages. It would be a departure from what OpenLiberty uses, but maybe that's okay? It looks like the Liberty container actually links to that guidance (the wasdev/ci.docker repo), though I'm not sure it's enforced.

**Comment by hsaunders0788** [comment]
@JusteenR  Talked to Chuck, and he said we could use that email, but that the Open Liberty repo is switching to a new method: 

```we are also in middle of changing to use cla-assistant

When we do we’ll change the cla language to simply click a button if they agree and it will record them through github login```

This new method has been approved at Walt's level, so I think we should be fine to use it, and I think we might be better off starting with that method since we don't have anything existing. Please reach out to Chuck Bridgham and Harry Hoots for more information on that and help with getting it running.

**Comment by arthurdm** [comment]
that sounds like a good approach! +1

**Comment by JusteenR** [comment]
They are currently trying to migrate to CLA Assistant and are reaching out to the Appsody team before they start their prototype at https://cla-assistant.io/appsody/appsody.
