### ISSUE TITLE
Resource service binding

### ISSUE THREAD

**Issue by arthurdm** [appsody/appsody-operator#206]
We now have support for app <-> app binding via the consumes / provides mechanism, with the `openapi` category.  

For non-app resources, such as DB, etc, we won't have a `provides` artifact, but we should be able to `consume` it by leveraging the [Service Binding Operator](https://github.com/redhat-developer/service-binding-operator) from Red Hat.  

At a high level view this works in the following steps:
- user deploys app with `consumes` (category equal to `resource` and corresponding params defined)
- Appsody Operator creates the corresponding YAML (`Kind: ServiceBindingRequest`) that the Service Binding Operator is watching for.  This assumes that the SB Operator is installed in the cluster.
- The YAML in the previous step also needs to be configured to produce the binding information (k8s Secret) in the schema / format that the Appsody Operator understands.   Some investigation needed here if both the items and the name of the Secret are configurable.
- From the consumer perspective, they will have the service information available in the exact same way as they do today for connecting to another app (either via secrets of file mounted [preferred])

We should take this opportunity to adopt any standards coming out from the Service Binding workgroup in terms of the structure of the mounted binding credentials.

For example, one proposal is to have ` /bindings/<cluster>/<namespace>/<service_name>`, although that doesn't have category / type - but perhaps that's not needed in order to properly consume the binding metadata.

**Comment by arthurdm** [comment]
fyi @sbose78

**Comment by arthurdm** [comment]
@navidsh - perhaps we start with a sample similar to [this one](https://github.com/redhat-developer/service-binding-operator/blob/master/examples/knative_postgresql_customvar/README.md), but using Open Liberty and our operator to drive the deployment.

**Comment by navidsh** [comment]
This issue isn't blocked anymore. Removing the tag

**Comment by arthurdm** [comment]
Closing this in favour of https://github.com/application-stacks/runtime-component-operator/issues/47
