### ISSUE TITLE
Operator failed to find service binding secret when different operators watching producer/consumer

### ISSUE THREAD

**Issue by navidsh** [appsody/appsody-operator#219]
### What did you do?

Deployed two `AppsodyApplication` using `appsody deploy` in two different namespaces, one consuming service produced from the other one. The two CRs are controlled by two different operators. 

### What did you expect to see?

Consumer to be able to bind to producer.

### What did you see instead?

The consumer's operator failed to find the producer's secret.

### Environment

* Appsody CLI version: `0.5.8`

* Appsody Stack: N/A

* Kubernetes version information: Minikube

**Comment by navidsh** [comment]
The problem happens because currently:
- The operator is only watching its own namespace, i.e., `namespace == operatorNamespace` in the below code:
https://github.com/appsody/appsody-operator/blob/bf71e585d8260c3f700092d44fc91899e10f321b/cmd/manager/main.go#L66-L75
- Appsody CLI only installs `Role`

But to have this scenario work:
- The operator should watch the whole cluster (even if `WATCH_NAMESPACE` is set to watch one namespace).
- Appsody CLI should install `ClusterRole` OR instruct users to install it for app2app service binding across multiple namespaces.

**Comment by arthurdm** [comment]
that seems reasonable @navidsh - so that we don't escalate privileges from the operator's installation.  

I wonder if this is something we could leverage the Service Binding Operator, since it should always have cluster bindings.  It could grab the Secret for us?

**Comment by navidsh** [comment]
> I wonder if this is something we could leverage the Service Binding Operator, since it should always have cluster bindings. It could grab the Secret for us?

Right, once we eventually change the impl to SBO, this wouldn't be an issue for the service binding part of the issue.

However, for watching/CRUDing resources in other namespaces, we would have the same problem for things like watching/reading image stream, getting Application CR across namespaces.

I wonder if we could have the operator running with Role/RoleBinding. But then relax RBAC **_only_** for certain resource groups? @arturdzm Do you know if it's possible?

**Comment by navidsh** [comment]
I'll be updating the user guide for all three operators to include info about the fact that the operators would need ClusterRole permissions in order to interact with resources in other namespaces.

**Comment by navidsh** [comment]
Delivered. Closing
