### ISSUE TITLE
Need support for named ports for service meshes

### ISSUE THREAD

**Issue by nastacio** [appsody/appsody-operator#227]
## Feature Request
Istio can provide special metric instrumentation for certain protocols, which also requires ports to have specific names.

Currently, AppsodyOperator automatically names ports as _port number_-_protocol_ and does not allow the user to provide a custom name, like specified here: https://istio.io/docs/ops/configuration/traffic-management/protocol-selection/

### Is your feature request related to a problem?
If someone is using Istio, yes, as it precludes full integration with Istio metric instrumentation.
All services created from Appsody have an Error mark next to them in the OpenShift Kiali console:
![image](https://user-images.githubusercontent.com/3278623/75616243-b4dfd000-5b1c-11ea-9a94-211165ec1f33.png)

### Describe the solution you'd like

AppsodyOperator should have a "service.port.name" field instead of always hardcoding the port name.

**Comment by arthurdm** [comment]
Sounds reasonable, and a good candidate for https://github.com/application-stacks/operator

**Comment by leochr** [comment]
@JusteenR Please look into adding this support, first to Application Stacks operator and then to Appsody Operator. Thank you.

**Comment by nastacio** [comment]
Istio 1.5 came out, which made this a far more serious problem. Essentially Istio is getting lost over the mislabeling of the port numbers and storing several of the "istio_requests_total" records in Prometheus with 'unknown' in fields like `destination_service_name` and `destination_service_namespace`, to the point where existing Grafana dashboards and Kiali visualizations no longer work.

Grafana:
![image](https://user-images.githubusercontent.com/3278623/76360335-2bd25100-62f3-11ea-9d7d-146da0baa109.png)

Kiali:
In this example, `nodejs-tracing` is continuously calling `jee-tracing` and `springboot-tracing`.

I deleted the appsody-operator deployment from the namespace to allow me to manually fix the port name on the `jee-tracing` service, while leaving `springboot-tracing` alone.

Note how Kiali correctly represents the outbound calls from `nodejs-tracing` to `jee-tracing`, whereas it cannot recognize the connectivity between `nodejs-tracing` and `springboot-tracing`:

![image](https://user-images.githubusercontent.com/3278623/76360430-5de3b300-62f3-11ea-8939-d5db66cf5a88.png)

That "PassthroughCluster" is Kiali's way of representing the unrecognized traffic coming out of `nodejs-tracing` towards `PassthroughCluster`.

**Comment by nastacio** [comment]
@JusteenR if you need a use case with Appsody, here are the apps I used for this:

https://github.com/ibm/icpa-opentracing

I can help you test it as needed.

**Comment by csantanapr** [comment]
In addition of service port name to have a protocol name with the suffix `http*` for http services.

For kiali and prometheus grafana boards to work correctly the deployment/pods need to have the labels `app` and `version`

**Comment by nastacio** [comment]
> In addition of service port name to have a protocol name with the suffix `http*` for http services.
> 
> For Istio kiali and Istio prometheus grafana boards to work correctly the deployment/pods need to have the labels `app` and `version`
> 
> I know is somewhere in the istio docs, but I can't find the specific page.

The labeling of the deployment is possible today through AppsodyOperator. I think you are talking about the `app` and `version` labels: 
https://istio.io/docs/ops/deployment/requirements/

**Comment by csantanapr** [comment]
Is possible to do it via appsody operator but it’s better if by default it puts this labels on the deployment

**Comment by nastacio** [comment]
> Is possible to do it via appsody operator but it’s better if by default it puts this labels on the deployment

It raises the interesting question of whether Appsody should provide first-class treatment for Istio conventions.

I am biased towards agreeing, just because I recently became a fan of Istio.

**Comment by arthurdm** [comment]
thanks a lot for your input @nastacio and @csantanapr!

I think it's a very interesting idea in terms of enhancing the Operator's support for Istio / Service Mesh. 
 Can you please open a feature request in our [upstream repo](https://github.com/application-stacks/runtime-component-operator)?   That functionality will make its way down to Appsody / Open Liberty Operators. 

This way we can keep this issue focused on the named ports.

**Comment by brightzheng100** [comment]
the named ports have become one of the K8s best practices so it's fine to make it baked by default.

But the labels can vary from Mesh to Mesh, from time to time, so I was still thinking to make them injectable by something like `appsody build -l <KEY1>=<VALUE1> -l <KEY2>=<VALUE2>`

**Comment by nastacio** [comment]
Just for reference, my workaround until the feature is released:

E.g. if the exposed port is "9080":

```
oc patch service <app-name> -p '{"spec":{"ports":[{"port": 9080, "name":"http"}]}}'
```

**Comment by chechuironman** [comment]
@nastacio does the workaround persists or is override by appsodyapplication CRD?

**Comment by leochr** [comment]
@chechuironman Named port support is now added (use `spec.service.portName` field). Please refer to [Service Ports](https://github.com/application-stacks/runtime-component-operator/blob/master/doc/user-guide.adoc#service-ports) section of the user guide for more info.

The operator watches the resources it creates, including Service and Route, to ensure that they are in the desired state expressed in AppsodyApplication CR. So any manual patch/modification of its resources will be reverted.
