### ISSUE TITLE
Operator does not add kappnav labels/annotations to KnativeService when createAppDefinition: true

### ISSUE THREAD

**Issue by dacleyra** [appsody/appsody-operator#232]
### What did you do?

Set, and deploy appsodyapplication with

```
  spec:
    createAppDefinition: true
    createKnativeService: true

```

### What did you expect to see?

Expect to see kappnav labels & annotations on the generated ksvc object

Granted, for this to be useful, in turn
- knativeserving would need to be propagating annotations & labels to the knativeservice child objects that kappnav monitors

### What did you see instead?

none

### Environment

* Appsody CLI version: 0.5.9

* Appsody Stack: java-microprofile

* Kubernetes version information: OCP 4.3

```
Client Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-12-24T05:49:02Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.2", GitCommit:"94e669a", GitTreeState:"clean", BuildDate:"2020-02-03T23:11:39Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
### Possible solution

maybe call UpdateAppDefinition
https://github.com/appsody/appsody-operator/blob/8fe99204ccebb6fd2e38020b00fc3468629d76b1/pkg/utils/utils.go#L63

within CustomizeKnativeService
https://github.com/appsody/appsody-operator/blob/8fe99204ccebb6fd2e38020b00fc3468629d76b1/pkg/utils/utils.go#L425

**Comment by navidsh** [comment]
@dacleyra kAppNac doesn't support auto-creation of `Applicaiton` CR. Once it supports, we will add the `auto-create` annotations.

We've documented this limitation in our [user-guide](https://github.com/application-stacks/runtime-component-operator/blob/master/doc/user-guide.md#kubernetes-application-navigator-kappnav-support):
> This feature is only available if you have kAppNav installed on your cluster. Auto creation of an application definition is not supported when Knative service is created

**Comment by arthurdm** [comment]
hey @navidsh - is this limitation because kAppNav doesn't support the Knative resources?   If so, could we create an issue in their board for it?

**Comment by navidsh** [comment]
@arthurdm yea, it's a limitation of kAppNav. I created a feature request issue in their repo: https://github.com/kappnav/issues/issues/181

FYI @dacleyra
