### ISSUE TITLE
HPA(Autoscale) doesn't work, relicas value is reverted by appsody after scaled out.

### ISSUE THREAD

**Issue by iamnogada** [appsody/appsody-operator#252]
## Bug Report
- Appsody Operator 0.4.0 on ocp4.3

### What did you do?
- Setting autoscale min/max value with cpu
- load traffic and invoke hpa
- pod number increased but reduce pod numbers to 1(reverted)

A clear and concise description of the steps you took (or insert a code snippet).

### What did you expect to see?
- pod has to increas along with load traffic and cpu usage increase.

A clear and concise description of what you expected to happen (or insert a code snippet). If possible, add `AppsodyApplication` CR.

### What did you see instead?
It should increate by hpa when load traffic

A clear and concise description of what you expected to happen (or insert a code snippet).

### Environment

* Appsody CLI version: 0.5.8

* Appsody Stack: java-spring-boot2 0.3.28

* Kubernetes version information: 1.16
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-26T06:16:15Z", GoVersion:"go1.14", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"b3bfb5a", GitTreeState:"clean", BuildDate:"2020-03-02T08:50:52Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

**Comment by leochr** [comment]
@iamnogada Thanks for opening the issue. There is an issue opened for this in the upstream project Runtime Component Operator. Once it's fixed, we'll pick it up in Appsody Operator : https://github.com/application-stacks/runtime-component-operator/issues/68

**Comment by arthurdm** [comment]
thanks @leochr - is there any workaround available for @iamnogada to try?

If it's an easy fix we could consider releasing 0.4.1 in Appsody / Open Liberty directly and push it into the 0.5.0 Runtime stream concurrently.

**Comment by leochr** [comment]
@arthurdm unfortunately, there isn't a workaround. Code changes at operator is necessary to address the issue. We'll try to address this as soon as possible.

We understand why this happens: The operator watches the sub-resources it creates (Deployment, Service, Route, etc) to ensure that it's in the desired state. When auto scaling is enabled, an HPA sub-resource is created, which tries to control the Deployment. This results in operator incorrectly reverting it back to the original state (using replicas definition).

**Comment by arthurdm** [comment]
great job fixing this @edavidj / @leochr - I think it can be closed now?

**Comment by leochr** [comment]
Yes. Closing as complete.
