### ISSUE TITLE
Add annotation field in the CR for the service key

### ISSUE THREAD

**Issue by arthurdm** [appsody/appsody-operator#41]
We need to be able to add annotations under the service key, for things like prometheus scrapping.

**Comment by navidsh** [comment]
Prometheus Operator on OpenShift does not support annotations for “scrape on” and ports. I confirmed this with some internal folks.

Based on the [operator's user guide](https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/getting-started.md#related-resources), a ServiceMonitor object should be created to describes the targets to be monitored by Prometheus.

Operator SDK has some helper methods to create ServiceMonitor objects from a service object.

**Comment by arthurdm** [comment]
So perhaps we can:
- add the ability to insert general annotations under the service key (even for other purposes)
- have a key under service (perhaps `service.enableMonitoring`) where under the covers our operator creates the ServiceMonitor?

**Comment by arthurdm** [comment]
Great job @navidsh, thanks.  I think we can close this one now?

**Comment by navidsh** [comment]
Delivered. Closing.
