### ISSUE TITLE
Support watching multiple namespaces

### ISSUE THREAD

**Issue by leochr** [appsody/appsody-operator#60]
We currently support watching a single namespace, own namespace and all namespaces in the cluster. 

Adding support to watch a set of namespaces will benefit users who want to watch more than one namespace, but not the entire cluster.

**Comment by arthurdm** [comment]
I have confirmed this is needed for our next release, to support multiple kabanero configurations.

**Comment by navidsh** [comment]
Next version of Operator SDK will have support for watching multiple namespaces out of the box. Until it releases a new version, we can use a workaround for this.

To get around this, the operator can watch all namespaces, and filter events using the namespaces it's watching.

The operator will read a comma-separated list of namespaces from `WATCH_NAMESPACE` env variable.

**Comment by arthurdm** [comment]
awesome @navidsh!  will we also update this page: https://github.com/appsody/appsody-operator/tree/master/deploy/releases/daily#installation?

**Comment by navidsh** [comment]
Good catch @arthurdm! I'll update that and will also add a `CHANGELOG.md` to record the changes we have been making.

**Comment by navidsh** [comment]
Delivered. Closing.
