### ISSUE TITLE
Architecture is missing from Knative Service

### ISSUE THREAD

**Issue by navidsh** [appsody/appsody-operator#64]
The generated Knative Service does not take into account the `architecture` field.

**Comment by navidsh** [comment]
Turned out it is not allowed to set `spec.template.spec.affinity` on Knative service or else Knative throws this error:
```
Internal error occurred: admission webhook "webhook.serving.knative.dev" denied the request: mutation failed: must not set the field(s): spec.template.spec.affinity
```

For the reference, Knative API only allows setting `ServiceAccountName`, `Containers` and `Volumes`. Other `PodSpec` fields such as `Affinity`, `DNSPolicy`, `RestartPolicy` and etc. cannot be set.

See [Knative](https://github.com/knative/serving/blob/release-0.7/pkg/apis/serving/fieldmask.go#L136-L181) for the full list.

**Comment by benzhonghai008** [comment]
@navidsh Hi, navidsh. Has this bug been fixed now ?
I encountered the same error in "serving.knative.dev/release: v0.10.0", when I try to deploy the sevice. The error message as following: 
```bash
SUPLMOSAN:knative iherb$ kubectl apply -f /tmp/productpage.yaml
Error from server (InternalError): error when creating "/tmp/productpage.yaml": Internal error occurred: admission webhook "webhook.serving.knative.dev" denied the request: mutation failed: must not set the field(s): spec.template.spec.affinity, spec.template.spec.containers[0].livenessProbe.httpGet.port, spec.template.spec.containers[0].readinessProbe.httpGet.port, spec.template.spec.dnsPolicy, spec.template.spec.restartPolicy, spec.template.spec.schedulerName, spec.template.spec.securityContext, spec.template.spec.terminationGracePeriodSeconds
```

While, I have checked the [Knative Serving API](https://knative.dev/docs/reference/serving-api/#serving.knative.dev/v1.RevisionTemplateSpec),
![image](https://user-images.githubusercontent.com/11565829/71511915-01b1eb00-28cf-11ea-803a-141a4bcc1ef4.png)
 It obviously supports Kubernetes core/v1.PodSpec, why error occurs ?

**Comment by navidsh** [comment]
Hi @benzhonghai008,

The error is coming from Knative Serving's admission webhook. [This is where ](https://github.com/knative/serving/blob/d3c14a10ba1448e4c400e4fad6b79b40ae31046f/pkg/apis/serving/k8s_validation.go#L246)the `PodSpec` validation code is called. [This is the](https://github.com/knative/serving/blob/7e47c0e27b03a3b921280a5e09b058424cbdda7b/pkg/apis/serving/fieldmask.go#L136-L181) actual `PodSpec` validation code. From the code, you can see that `spec.template.spec.affinity` is not allowed to be set.

The reason behind this code would be a question for the Knative Serving community.

**Comment by benzhonghai008** [comment]
Got it. Thanks for your patience.
