### ISSUE TITLE
Upgrade Operator SDK libraries

### ISSUE THREAD

**Issue by navidsh** [appsody/appsody-operator#93]
Once Operator SDK releases a new version > `0.10.0`, we should consider upgrading Appsody Operator to use the new libraries.

Operator SDK recently upgraded `controller-runtime` to v0.2.0 which is needed for adding admission webhook. Also, the new SDK has new helper utils for `ServiceMonitor` creation and metering support.

**Comment by arturdzm** [comment]
Updated to Operator SDK `0.12.0` in `0.3.0` release
