### ISSUE TITLE
Additional automated e2e tests for Appsody Operator

### ISSUE THREAD

**Issue by navidsh** [appsody/appsody-operator#95]
Add more e2e tests for the following areas:
- [x] Autoscaling
- [x] Persistence
- [ ] ~ConfigMap default and constants~ To be tracked in #110
- [ ] ~Knative~ To be tracked in #111

**Comment by edavidj** [comment]
Persistence tests are included in PR #103

**Comment by navidsh** [comment]
Thanks guys for delivering the tests. Closing this one in the favour of new #110 and #111.
